### ISSUE TITLE
Try and Refine QuickStart

### ISSUE THREAD

**Issue by snowgy** [TheDataStation/ver#47]
Earlier I included a draft quickstart here https://github.com/TheDataStation/ver/blob/add_dataset/quick_start.md
There are a few objectives for revising the quickstart.
- Rewrite the quickstart using commands defined in the ver_cli.py
- Get rid of the export statement
- Add more explanations

**Comment by zaki-indra** [comment]
I already add a PR regarding this issue at #50.
